### ISSUE TITLE
allow user to define temperature

### ISSUE THREAD

**Issue by swharden** [swharden/JLJP#2]
- [x] Modify the formula to accomodate a custom temperature
- [ ] Add a temperature box to the GUI

**Comment by swharden** [comment]
I exposed `Ion.temperatureC` so we just need to add a GUI box to let the user set it.

https://github.com/swharden/JLJP/blob/906bfe5bf5e0f7249f828fec9b4565e143bf5124/src/Ion.java#L8-L13

**Comment by dbrogioli** [comment]
Handling the temperature is not staightforward. The main effect of temperature changes on the liquid junction potential is to alter the diffusion coefficients (or equivalently the mobilities). In turn, the variation of diffusion coefficient is mostly determined by i) the variation of viscosity of the solvent and ii) the variation of the interaction between the ion and its solvation shell. The term kT in the formulas represent only a minor effect of temperature. Thus it is necessary to warn the user that the mobilities automatically filled by the program refer to room temperature, although different values of kT can be ideally input.

**Comment by swharden** [comment]
> mobilities automatically filled by the program refer to room temperature

I did not consider this! It seems that setting temperature is a lot more complicated than I initially thought, so I'm happy leaving things as they are. 

Thanks for looking into it!

**Comment by dbrogioli** [comment]
Being able to calculate at various temperatures would be very useful. If the user knows the mobilities at a given temperature, he/she can input the values, but then he/she must also change the temperature T used for calculating k_B T. I suggest the following. First add a field where the user can add the temperature. Then, when the calculation is performed, the program checks if the temperature is set accordingly to the temperature at which the ion mobilities are given and, possibly, gives a warning. Currently, the mobilities are at 25°C, so, if the user sets - say - 50°C, the program warns: "the ion mobilities are defined at a temperature different from 50°C". If we implement the ion mobility table as a database, including the temperature at which the mobility is taken, the program could check the coherence between the set T and the temperature at which the ion mobility refers to.

**Comment by swharden** [comment]
I experimented with the ion set in the JLJP screenshot and ran LJP calculations at temperatures 0C through 50C using mobilities for 3 different temperatures (from [Langes Handbook of Chemistry](http://fptl.ru/biblioteka/spravo4niki/dean.pdf)). 

![image](https://user-images.githubusercontent.com/4165489/74702451-10829300-51d8-11ea-97ba-9bbdf1571e08.png)


Interestingly, the KT effect from a swing of 25C is about 4 times larger than the effect of using mobilities reported 25C apart. I take this to mean that both are important, but adding user input for KT temperature has a bigger effect on final LJP than having them modify the mobility table.

Do you think discussion on this topic would be useful for the manuscript?

[code used to produce this graph](https://github.com/swharden/LJPcalc/blob/f07cc0362791481234d60b9b06545b0ff20b6d2a/src/LJPresearch/Program.cs#L39-L85
)
