### ISSUE TITLE
add citation to mobility table

### ISSUE THREAD

**Issue by swharden** [swharden/JLJP#3]
Where did mobility table come from? This should be cited in the code.

https://github.com/swharden/JLJP/blob/b585ab99d78f39960f85b17988374f3445b7dadb/src/Ion.java#L29-L125

**Comment by dbrogioli** [comment]
I added a comment with the name of the bibliographic source:

https://github.com/swharden/JLJP/blob/ff32b9ee12d99d94d9cbe1affb8364474ef5cc5f/src/Ion.java#L60-L62

**Comment by swharden** [comment]
@dbrogioli the addition ff32b9ee12d99d94d9cbe1affb8364474ef5cc5f looks great, thanks!

**Comment by saglag** [comment]
**Original Papers**
Application - Ng and Barry 1995: https://www.sciencedirect.com/science/article/pii/016502709400087W
Review - Barry and Lynch 1991: https://link.springer.com/article/10.1007/BF01870526

Note: The review uses values sourced from Langes Handbook of Chemistry (1985), edited by JA Dean, and Electrolyte Solutions (1968), by Robinson and Stokes.

**Comment by swharden** [comment]
Thanks for pointing these papers out @saglag! 

It's also reassuring to run some of their numbers and see their LJPs are consistent with ours (even though their theoretical values use the Henderson equation). References like this might be a good source for known ion sets / LJPs that can be used to create tests as discussed in #5 

![image](https://user-images.githubusercontent.com/4165489/74173260-d75a8980-4bff-11ea-966e-473463068c2e.png)

**Comment by swharden** [comment]
> Note: The review uses values sourced from Langes Handbook of Chemistry (1985), edited by JA Dean, and Electrolyte Solutions (1968), by Robinson and Stokes.

@saglag it looks like a PDF of this book is available http://fptl.ru/biblioteka/spravo4niki/dean.pdf but I'm having trouble locating these values. You're more familiar with chemistry than I am - am I overlooking something?

**Comment by swharden** [comment]
The review paper shows a table:

![image](https://user-images.githubusercontent.com/4165489/74178005-d417cb80-4c08-11ea-86a9-db470919a49d.png)
...
![image](https://user-images.githubusercontent.com/4165489/74178154-193bfd80-4c09-11ea-8ded-1a34422cb67d.png)

_Mobility in this chart is expressed relative to that of K+. For example, relative ionic mobility of H+ (4.76) is mobility of H+ (350.1) divided by that for K+ (73.5)_

It looks like they calculate ion mobility from _[equivalent molar conductivity](https://en.wikipedia.org/wiki/Molar_conductivity)_ which is **TABLE 8.32** of _Langes Handbook of Chemistry_ which is available as a PDF: http://fptl.ru/biblioteka/spravo4niki/dean.pdf

There are 3 temperatures available to choose from so maybe one day we can add a feature to let the user calculate LJP at different temperatures after all (#2)

![image](https://user-images.githubusercontent.com/4165489/74176905-a03ba680-4c06-11ea-9774-7e1e948d9d04.png)
![image](https://user-images.githubusercontent.com/4165489/74179257-12ae8580-4c0b-11ea-9bad-7f9974993e07.png)
![image](https://user-images.githubusercontent.com/4165489/74179161-e98df500-4c0a-11ea-8a27-15052997fb9a.png)

**Comment by swharden** [comment]
@saglag thanks for the tip! That got me the rest of the way there.

### Source (PDF)
TABLE 8.32 of _Langes Handbook of Chemistry_:\
http://fptl.ru/biblioteka/spravo4niki/dean.pdf

### Calculation
```python
def showMobilityOfIon(name, charge, conductance):
    Av = 6.02e23 # avogadro's number
    F = 1.6e-19 # elementary charge
    mobility = conductance / (Av * pow(F, 2) * abs(charge))
    print("%s mobility: %E" % (name, mobility))

showMobilityOfIon("Ag+", 1, 61.9e-4)
showMobilityOfIon("Cl-", -1, 76.31e-4)
showMobilityOfIon("Ca++", 2, 59.5e-4)
showMobilityOfIon("NH2SO3-", -1, 48.6)
```

### Sample Output
```
Ag+ mobility: 4.016559E+11
Cl- mobility: 4.951594E+11
Ca++ mobility: 1.930414E+11
NH2SO3- mobility: 3.153551E+15
```

**Comment by dbrogioli** [comment]
The algorithm uses the mobilities but also the temperature T, independently. I think that the possibility of selecting the temperature T is useful. For example, a user can take the ion mobilities from a handbook, say at 70°C, and input them manually into JLJP. Then he/she wants also to change the value of T used in the calculations (the term k_BT).

So, I suggest to put an input field for changing the temperature! Together with this, I suggest to clarify that changing T does not account for all the temperature change effects, so the user is aware that he/she has to take care of changing the mobilities according to the temperature.

For the future, having a database of mobilities at various temperatures, which can be expanded easily with contributions from users, would be excellent!

**Comment by swharden** [comment]
> The algorithm uses the mobilities but also the temperature T, independently. I think that the possibility of selecting the temperature T is useful. For example, a user can take the ion mobilities from a handbook, say at 70°C, and input them manually into JLJP. Then he/she wants also to change the value of T used in the calculations (the term k_BT).
> 
> So, I suggest to put an input field for changing the temperature! Together with this, I suggest to clarify that changing T does not account for all the temperature change effects, so the user is aware that he/she has to take care of changing the mobilities according to the temperature.

This sounds good! Maybe we could add a temperature box in the GUI with a button next to it that says _details_ which launches a pop-up dialog that explains this.

> For the future, having a database of mobilities at various temperatures, which can be expanded easily with contributions from users, would be excellent!

I like this idea too! Having this project open source makes it a lot easier for users to not only add their own mobilities, but also push their changes back to the main project so everyone benefits from them.

**Comment by swharden** [comment]
Discussion related to adding a temperature option can continue in #2 now that this mobility citation issue is resolved.

**Comment by swharden** [comment]
Here are some additional mobility tables useful for #10 
https://medicalsciences.med.unsw.edu.au/research/research-services/ies/ionicmobilitytables
