### ISSUE TITLE
remove JSci dependency

### ISSUE THREAD

**Issue by swharden** [swharden/JLJP#8]
JLJP currently depends on JSci to parse strings and solve for LJP in non-ideal conditions. 

Let's assume conditions are ideal so we can eliminate JSci. 

Later we can come back and add a native code to parse equations and solve in non-ideal conditions.

**Comment by dbrogioli** [comment]
With 09d3e73 , I removed completely JSci. I substituted the symbolic calculation with a much simpler implementation, which is however more than enough for JLJP. So the non-ideal activity can still be handled. JSci was needed also for linear algebra; I substituted these functions with the class Linalg, which only contains static methods for making linear algebra using double[] and double[][] as vectors and matrices.
Please, check if everything is still working. In case there are differences in the behaviour, they could be due to errors I made.
A fundamenral problem however is still present: the non-ideality is only partially handled and in the future a more general representation should be given.

**Comment by swharden** [comment]
> With 09d3e73 , I removed completely JSci. 

That's great news! It looks like it was a lot of work. Thanks for looking into it!

> I substituted the symbolic calculation with a much simpler implementation (more than enough for JLJP)

>  JSci was needed also for linear algebra; I substituted these functions with the class Linalg, which only contains static methods for making linear algebra using double[] and double[][] as vectors and matrices.

Where did this new code come from? Do we need to credit its source or worry about its license?

> non-ideal activity can still be handled ... in the future a more general representation should be given.

~~Does this mean the user can still enter custom expressions for cdadc as it is now? \
If so, an example of this on the main readme would be helpful.~~

_EDIT: I see custom expressions are still handled (since the tests pass). Suitable examples are Example.java and the test files themselves._

> Please, check if everything is still working. In case there are differences in the behaviour, they could be due to errors I made.

At first glance it looks great! Thanks again for all your effort on this. I'll check it for accuracy as I add tests (#5). I'll leave this issue open until I get the tests working again.

---

_One note about git - moving forward be sure you fetch and pull on your end before working on the source code again. This ensures the source code on your machine is always the latest. If you're working on an old version of the source, commit changes, then go to push it you'll get merge conflicts you have to resolve manually which aren't fun. For example, I just modified Jljp.java, so you'll want to make sure your system has the latest version before you go to modify it again._

**Comment by swharden** [comment]
> Please, check if everything is still working. In case there are differences in the behaviour, they could be due to errors I made.

Tests in (in /test/) still pass so we can be pretty confident it works 😎 

```
JUnit version 4.13
.....
Time: 0.276

OK (5 tests)
```

**Comment by dbrogioli** [comment]
>> I substituted these functions with the class Linalg
>Where did this new code come from? Do we need to credit its source or worry about its license?

The Linalg code is mine; I'm using it time to time, just for me, and it is the first time that it enters in a public project. It is absolutely minimal. No license is needed. In the future, in case we need something more advanced, we could use the "apache common math" stuff, if you think that it is fine.

**Comment by swharden** [comment]
> The Linalg code is mine; I'm using it time to time, just for me, and it is the first time that it enters in a public project. It is absolutely minimal. No license is needed. In the future, in case we need something more advanced, we could use the "apache common math" stuff, if you think that it is fine.

Sounds good!  What about all the files in the "symbolic" folder, did you write those from scratch too?

I ask because I'm working to translate all these files to C# for [LJPcalc](https://github.com/swharden/LJPcalc) and I want to make sure I do it all properly with respect to licensing before I upload it.

**Comment by dbrogioli** [comment]
This requires some explanation.

The symbolic package is one of the many versions I wrote of the same stuff, thus it bears similarities with the JSci math.symbolic package. There are significant differences: 

- The new one is only dealing with real numbers, represented by double values, while the JSci package worked on generic fields and groups;
- The variables are simply represented by String s;
- The .substitute() and .evaluate() methods follow completely different logics.

The part in common with JSci is the parsing. But this common part is simply the representation of symbolic mathematical formulas in the BNF notation; this cannot be claimed to be covered by any copyright.

So said, I leave to you the decision, if you want to add a comment saying that a similar symbolic package was also found in an old release of JSci. I would not...

However is another problem. What will happen if we want to write another project, which also makes use of "symbolic"? It would be weird to acknowledge JLJP just for "symbolic" package. The same goes foe Linalg. Any suggestion?

**Comment by swharden** [comment]
Hi @dbrogioli, thanks for your thorough explanation! Here are a few of my thoughts.

I agree with you that there's no copyright or licensing issue, and a comment pointing to JSci from your symbolic package is not needed.

What should be done with the Symbolic and LinAlg packages? There's no right answer, but here's what I'd recommend based on my own experience. _The short answer: It's fine how it is for now._

* If you write code for JLJP that might be useful to other projects later, but those projects aren't public yet, keep all the code inside the JLJP project but create sub-folders for each potential package to make them easy to separate later.
  * Inside that folder you can create a readme.md file which clearly documents what the package is for and how to use it
  * Inside that folder you can create a LICENSE file too
  * Optional: Inside that folder you can create jUnit tests. These serve the same role as "Example.java" (showing potential users how to interact with the package) but they're even better because they couple inputs with expected outputs.

* Once another public project has a need for that package, pull the small package out of JLJP and put it in its own repository
  * Since that package folder already has its own readme, license, and tests ready to go, it's little effort to make the package its own repository.
  * Avoid the temptation to do this too early since maintaining multiple repositories takes extra effort. Rather than have dozens of little projects online, I find it's best to wait until they're truly needed by multiple public projects.
  * If the packages are truly useful, consider making them packages in a package manager like Maven. This way users can grab the library without having to find the project online and download source code.
  * If you want an easy place to store packages you write that you don't think anyone but you will use, you can create a repository called "BrogioliTools" or something, and in there you can store a bunch of small packages in individual folders. With one git command you can download all your tools on any computer.

PS: I created a new "annotated" branch of JLJP https://github.com/swharden/JLJP/branches which I refactored and thinned-out. It doesn't use your symbolic library (it assumes cdadc is always 1.0). This is what I'll translate to C# for [LJPcalc](https://github.com/swharden/LJPcalc), and some time after everything is working there I can go back and add support for cdadc equations (translating the Symbolic library to C# at that later time).

Let me know if you have any further questions!

**Comment by swharden** [comment]
Following up on this, I translated the Linalg module to C#

https://github.com/swharden/LJPcalc/blob/master/src/LJPmath/Linalg.cs
https://github.com/swharden/LJPcalc/blob/master/src/LJPtest/LinalgTest.cs

The tests are not complete in that they don't challenge functions like `Sum()` or `Transpose()` against known expected output.
